# Default PROXD settings
#focal_length_x: 1060.53
#focal_length_y: 1060.38
#camera_center_x: 951.30
#camera_center_y: 536.77

# From SLP README.ME RGB
#focal_length_x: 902.6
#focal_length_y: 877.4
#camera_center_x: 278.4
#camera_center_y: 525.1

# From SLP README.ME Depth
focal_length_x: 367.8
focal_length_y: 367.8
camera_center_x: 208.1
camera_center_y: 259.7

#depth_loss_weight: 0.0

flip: False
camera_mode: 'fixed'
output_folder: './slp_fits'

side_view_thsh: 55 # If shoulders are narrower than this, try both orientations

use_vposer: False
vposer_ckpt: "models/vposer_v1_0/"
part_segm_fn: "models/smplx_parts_segm.pkl"

height_w: 50
weight_w: 100

batch_size: 24 # We can do all 45 poses at once?
optim_type: 'adam'
#ftol: 1e-12
ftol: 0
gtol: 1e-9
lr: 0.01
maxiters: 100


# LBFGS with line search
#optim_type: 'lbfgsls'
#ftol: 1e-9
#gtol: 1e-9
#lr: 0.1
#maxiters: 30

###################
contact: False
contact_angle: 45
rho_contact: 5e-2
contact_loss_weights:
    - 0.0
    - 0.0
    - 0.0
    - 0.0
    - 0.0
    - 0.0
    - 1e4
load_scene: False
###################
sdf_penetration: True
sdf_penetration_weights:
    - 0.0
    - 0.0
    - 0.0
    - 0.0
    - 0.0
    - 200
    - 100

trans_opt_stages:
    - 2
    - 3
    - 4
    - 5
    - 6
mask_on_color: False
read_depth: True
read_mask: True
# Depth
init_mode: 'scan'   # This picks the mean of the depth image, but since we 'dont have this', lets just try something
m2s: True
rho_m2s: 10e-1   # Approximately controls the "range" of the loss function
m2s_weights:
    - 1.0
    - 1.0
    - 100
    - 500
    - 1000
    - 5000
    - 5000

s2m: True
rho_s2m: 4e-1
s2m_weights:
    - 1.0
    - 1.0
    - 100
    - 500
    - 500
    - 500
    - 500

shape_weights:
    - 100
    - 50
    - 10
    - 5
    - 5
    - 5
    - 5
data_weights:   # Keypoints
    - 1
    - 1
    - 1
    - 1
    - 1
    - 1
    - 1

###################
dataset: 'openpose'
joints_to_ign:
    - 15
    - 16
    - 17
    - 18
    - 19
    - 20
    - 21
    - 22
    - 23
    - 24
#    - 0 # Ignore the head since SLP annotates higher than the nose
prior_folder: 'priors'
model_folder: 'models'
result_folder: 'results'
gender: "male"
gender_lbl_type: 'gt'   # Patrick: use gender in keypoints file
use_height_weight: True
model_type: 'smpl'
# Flag for using the GPU
use_cuda: True
float_dtype: "float32"
use_joints_conf: True
use_pca: True
use_hands: False
use_face: False
flat_hand_mean: False
# The number of mixture components for the pose prior
num_gaussians: 8
body_prior_type: 'smpl_limit'
left_hand_prior_type: l2
right_hand_prior_type: l2
jaw_prior_type: 'l2'
num_pca_comps: 12
# The constant for the robust loss function
rho: 100
interpenetration: True
df_cone_height: 0.0001
# Upper arms and Spine 2
# Neck and jaw
ign_part_pairs: ["9,16", "9,17", "6,16", "6,17", "1,2", "12,22"]
penalize_outside: True
max_collisions: 128

interactive: True
visualize: False
# Relative change in loss value
body_pose_prior_weights:
    - 100
    - 100
    - 100
    - 100
    - 100
    - 200
    - 200
coll_loss_weights:
    - 0.0
    - 0.0
    - 0.0
    - 0.0
    - 0.0
    - 0.1
    - 1.0
